apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-config
  namespace: {{ .Release.Namespace | default "default"}}
  labels:
    app: graphql
data:
  HASURA_GRAPHQL_DEV_MODE: "true"
  HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
  HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
  HASURA_GRAPHQL_NO_OF_RETRIES: "10"
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous