{{ if .Values.graphql.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app: graphql
spec:
  type: NodePort
  selector:
    app: graphql
  ports:
	{{- .Values.graphql.service.ports | toYaml | nindent 2 -}}
---
{{ end }}