apiVersion: v1
kind: Secret
metadata:
  name: graphql-secrets
  namespace: default # change to match namespace of the helm install
type: Opaque
stringData:
  HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:HKdZdFcZv3ke2ZqYdcfJg0vusdPm@db:5432/cdefense # change after helm install
  HASURA_GRAPHQL_ADMIN_SECRET: DMcbjEaJ3CSeAoj4ZYkUgLRP # change after helm install
  HASURA_GRAPHQL_JWT_SECRET: '{ "type": "RS256", "jwk_url": "http://keycloak/auth/realms/cdefense/protocol/openid-connect/certs" }'
