apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: aymazWsEHmJFpyYXQz2yLoUg # change after helm install
  KEYCLOAK_ADMIN_CLIENT_SECRET: 3KnxhT7x-7sRH-Rbj5-7311-V5R9q9cAEuHg # change after helm install