apiVersion: v1
kind: ConfigMap
metadata:
  name: authservice-config
  labels:
    app: keycloak
data:
  AUTH_DEPLOYMENT_MODE_DOCKER: "true"
  NEW_RELIC_APP_NAME: cdefense
  DOMAIN: "cdefense.clouddefenseai.com"