apiVersion: v1
kind: Service
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  type: {{ .Values.authservice.service.type }}
  selector:
    app: authservice
  ports:
    {{- .Values.authservice.service.ports | toYaml | nindent 2 -}}
