apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-role
rules:
- apiGroups: ["*"]
  resources: 
    - "pods/log" 
    - "pods"
  verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-rolebinding

roleRef:
  apiGroup: ""
  kind: Role
  name: pod-role
subjects:
- kind: ServiceAccount
  name: default

  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:

  name: job-role
rules:
- apiGroups: ["*"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-rolebinding

roleRef:
  apiGroup: ""
  kind: Role
  name: job-role
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
