version: "release-4.6.2"
domain: clouddefenseai.com
hostname: console.clouddefenseai.com

cluster:
  type: eks
  region: us-west-2
  zones: |
    [ 'us-west-2a', 'us-west-2b', 'us-west-2c' ]

ingress:
  enabled: true
  type: "alb"
  alb:
    scheme: internet-facing

aws:
  certificatearn: ""

sentry:
  env: prod

uptime:
  nodeSelector: external
  tolerations: []
  enabled: false
  hostname: status.clouddefenseai.com

db:
  nodeSelector: db
  tolerations: []
  type: "internal"
  replicas: 1
  image: postgres
  version: "14"
  user: "postgres"
  name: "cdefense"
  external:
    host:
      name: ""
    secondary:
      host:
        name: ""
  service:
    type: NodePort
    ports:
    - port: 5432
      targetPort: 5432
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

keycloak:
  nodeSelector: auth
  tolerations: []
  replicas: 1
  image: quay.io/keycloak/keycloak
  version: "18.0.0"
  user: authadmin
  service:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 8080
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

authservice:
  nodeSelector: auth
  tolerations: []
  replicas: 1
  image: cdefense/auth-service
  environment: dev
  realm: cdefense
  service:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 8080

graphql:
  nodeSelector: api
  tolerations: []
  image: cdefense/graphql
  service:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 8080

api:
  nodeSelector: api
  tolerations: []
  image: cdefense/scan-api
  service:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 8080
  cyberthoth:
    image: cdefense/cyberthoth:dev
  fullscan:
    image: cdefense/fullscan:prod
  data:
    region: us-east-1
    bucket: cdefense-vulnerability-data-new
    endpoint: https://cdefense-vulnerability-data-new.s3.us-east-1.amazonaws.com
  logs:
    region: us-west-2
    bucket: cdefense-cli-logs
  job:
    nodeSelector:
      key: label
      value: job

data:
  nodeSelector: api
  tolerations: []
  image: cdefense/scan-data

newapi:
  nodeSelector: api
  tolerations: []
  replicas: 1
  image: cdefense/new-api
  version: "latest"
  service:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 8080
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

alertservice:
  nodeSelector: api
  tolerations: []
  replicas: 1
  image: cdefense/alert-service
  version: "latest"
  service:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 8080
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

recommendation:
  hostname: recommendation.clouddefenseai.com
  nodeSelector: api
  tolerations: []
  replicas: 1
  image: cdefense/recommendation-service
  version: "latest"
  service:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 3000
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

web:
  nodeSelector: web
  tolerations: []
  replicas: 1
  image: cdefense/webconsole
  service:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 80

admin:
  backend:
    nodeSelector: auth
    tolerations: []
    replicas: 1
    image: cdefense/admin-ui-be
    version: "latest"
    service:
      type: NodePort
      ports:
      - name: http
        port: 80
        targetPort: 8080
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
  frontend:
    nodeSelector: web
    tolerations: []
    replicas: 1
    image: cdefense/admin-ui-fe
    version: "latest"
    service:
      type: NodePort
      ports:
      - name: http
        port: 80
        targetPort: 80
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

acs:
  enabled: false
  backend:
    nodeSelector: api
    tolerations: []
    replicas: 1
    image: cdefense/acs
    version: "latest"
    service:
      type: NodePort
      ports:
      - name: http
        port: 80
        targetPort: 8080
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
  frontend:
    nodeSelector: web
    tolerations: []
    replicas: 1
    image: cdefense/acs_fe
    version: "latest"
    service:
      type: NodePort
      ports:
      - name: http
        port: 80
        targetPort: 4200
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
