{{ if .Values.pdfgenerator.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-generator
  namespace: {{ .Release.Namespace | default "default"}}
spec:
  selector:
    matchLabels:
      app: pdf-generator
  # replicas: {{ .Values.pdfgenerator.replicas }}
  strategy:
    type: Recreate
    # type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 0%
    #   maxSurge: 25%
  template:
    metadata:
      labels:
        app: pdf-generator
    spec:
      {{- if .Values.pdfgenerator.nodeSelector }}
      nodeSelector:
        label: {{ .Values.pdfgenerator.nodeSelector }}
      {{- end }}
      {{- if .Values.pdfgenerator.tolerations }}
      tolerations:
{{ toYaml .Values.pdfgenerator.tolerations | indent 8 }}
      {{- end }}
      imagePullSecrets:
      - name: regcred
      containers:
      - name: pdf-generator
        image: {{ .Values.pdfgenerator.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        # resources:
        #     requests:
        #       memory: {{ .Values.pdfgenerator.resources.requests.memory}}
        #       cpu: {{ .Values.pdfgenerator.resources.requests.cpu }}
        #     limits:
        #       memory: {{ .Values.pdfgenerator.resources.limits.memory}}
        #       cpu: {{ .Values.pdfgenerator.resources.limits.cpu }}

{{ end }}