apiVersion: v1
kind: ConfigMap
metadata:
  name: scan-server-config
  namespace: {{ .Release.Namespace | default "default"}}
  labels:
    app: api
data:
  FULL_SCAN_DOCKER_IMAGE: {{ .Values.api.fullscan.image }}:{{ .Values.version }}
  API_SCAN_DOCKER_IMAGE: {{ .Values.api.apiscan.image }}:{{ .Values.version }}
  DAST_SCAN_DOCKER_IMAGE: {{ .Values.api.dast.image }}:{{ .Values.version }}
  KUBERNETES_NODESELECTOR_KEY: {{ .Values.api.job.nodeSelector.key }}
  KUBERNETES_NODESELECTOR_VALUE: {{ .Values.api.job.nodeSelector.value }}
  DATA_VFEED_SQLITE_FULL_REFRESH_CRON_EXPRESSION: "0 */2 * * *"
  CVE_LOOKUP_DB_TYPE: VFEED
  KEYCLOAK_ENABLED: "true"
  MICRONAUT_SECURITY_ENABLED: "true"
  MICRONAUT_SECURITY_TOKEN_JWT_BEARER_ENABLED: "true"
  KAFKA_SERVERS: "kafka:9092"
  MICRONAUT_SECURITY_ENABLED: "true"
  MICRONAUT_SECURITY_TOKEN_JWT_BEARER_ENABLED: "true"
  AWS_S3_REGION: {{ .Values.api.data.region }}
  AWS_S3_BUCKET: {{ .Values.api.data.bucket }}
  AWS_S3_ENDPOINT: {{ .Values.api.data.endpoint }}
  AWS_SCAN_S3_REGION: {{ .Values.api.logs.region }}
  AWS_SCAN_S3_BUCKET: {{ .Values.api.logs.bucket }}
  AWS_DAST_UPLOAD_S3_REGION: {{ .Values.api.dast.region }}
  AWS_DAST_UPLOAD_S3_BUCKET: {{ .Values.api.dast.bucket }}
  VULNERABILITY_SCRAPER_SERVICE_HOST: {{ .Values.api.vuln.host}}
  MAX_SCAN_PER_USER: "10"
  ONLINE_SCAN_POOL_SIZE: "20"
  CDEFENSE_BACKEND_URL: "http://newapi"
  CLOUDDEFENSE_NEWAPI_BASE_URL: https://{{ .Values.hostname }}/
  K8_RESOURCES_REQUEST_MEMORY: "3Gi"
  K8_RESOURCES_REQUEST_CPU: "2000m"
  K8_RESOURCES_LIMIT_MEMORY: "4Gi"
  DATAJOB_WEBHOOK_URL: "https://discord.com/api/webhooks/1006160865386582077/HndjuqofW-wYXspUb5_iv-AJN46UojZZvQDksz1a2cgvx1Q1lUJkdZ_IhZrlsh_ytKKO"
  PROFILER_WEBHOOK_URL: "https://discord.com/api/webhooks/1102883054806114375/DwZqyzMTpYf66kMyQ47b7lgFLNFGfqmxQxEBfnfOZtH6cMJIFzoNw17pmQnG9OmNk9Tv"
  CLOUDDEFENSE_SENDGRID_EMAIL: "support-noreply@clouddefense.ai" 