apiVersion: v1
kind: ConfigMap
metadata:
  name: scan-server-config
  namespace: {{ .Release.Namespace | default "default"}}
  labels:
    app: api
data:
  FULL_SCAN_DOCKER_IMAGE: {{ .Values.api.fullscan.image }}:{{ .Values.version }}
  API_SCAN_DOCKER_IMAGE: {{ .Values.api.apiscan.image }}:{{ .Values.version }}
  DAST_SCAN_DOCKER_IMAGE: {{ .Values.api.dast.image }}:{{ .Values.version }}
  KUBERNETES_NODESELECTOR_KEY: {{ .Values.api.job.nodeSelector.key }}
  KUBERNETES_NODESELECTOR_VALUE: {{ .Values.api.job.nodeSelector.value }}
  DATA_VFEED_SQLITE_FULL_REFRESH_CRON_EXPRESSION: "0 */2 * * *"
  CVE_LOOKUP_DB_TYPE: VFEED
  KEYCLOAK_ENABLED: "true"
  MICRONAUT_SECURITY_ENABLED: "true"
  MICRONAUT_SECURITY_TOKEN_JWT_BEARER_ENABLED: "true"
  KAFKA_SERVERS: "kafka:9092"
  MICRONAUT_SECURITY_ENABLED: "true"
  MICRONAUT_SECURITY_TOKEN_JWT_BEARER_ENABLED: "true"
  AWS_S3_REGION: {{ .Values.api.data.region }}
  AWS_S3_BUCKET: {{ .Values.api.data.bucket }}
  AWS_S3_ENDPOINT: {{ .Values.api.data.endpoint }}
  AWS_SCAN_S3_REGION: {{ .Values.api.logs.region }}
  AWS_SCAN_S3_BUCKET: {{ .Values.api.logs.bucket }}
  AWS_DAST_UPLOAD_S3_REGION: {{ .Values.api.dast.region }}
  AWS_DAST_UPLOAD_S3_BUCKET: {{ .Values.api.dast.bucket }}
  VULNERABILITY_SCRAPER_SERVICE_HOST: {{ .Values.api.vuln.host}}
  MAX_SCAN_PER_USER: "10"
  ONLINE_SCAN_POOL_SIZE: "20"
  CDEFENSE_BACKEND_URL: "http://newapi"
  CLOUDDEFENSE_NEWAPI_BASE_URL: https://{{ .Values.hostname }}/
  K8_RESOURCES_REQUEST_MEMORY: {{ .Values.api.job.resource.memory.request }}
  K8_RESOURCES_REQUEST_CPU: {{ .Values.api.job.resource.cpu.request }}
  K8_RESOURCES_LIMIT_MEMORY: {{ .Values.api.job.resource.memory.limit }}
  # DATAJOB_WEBHOOK_URL: "https://discord.com/api/webhooks/1006160865386582077/HndjuqofW-wYXspUb5_iv-AJN46UojZZvQDksz1a2cgvx1Q1lUJkdZ_IhZrlsh_ytKKO"
  PROFILER_WEBHOOK_URL: "https://discord.com/api/webhooks/1327287754400464907/Qw7BNZeb_baPqxy-aKBG7VfWXSSdwHvUoPcahrurG6bCxGBnfaYu8iiJWdpKVXACTial"
  STATISTIC_WEBHOOK_URL: "https://discord.com/api/webhooks/1121016075799253063/6dAOW8JvKo3rHudlcwtcNFR0gMfLvfIWFFTAQTXxORwML7Y58RzDBjfjztqa9DZ6WmXw"
  CLOUDDEFENSE_SENDGRID_EMAIL: "support-noreply@clouddefense.ai" 
  MICRONAUT_ENVIRONMENTS: {{ .Values.api.environment | default "dev"  }}
  ALERT_SERVICE_URL: "http://alertservice"
  CUSTOM_ALLOWED_ORIGIN: {{ .Values.api.origin | default "https://cdefense.clouddefenseai.com" }}
  NODEJS_SERVER: "http://pdf-generator/"
  AI_SAST_API_URL: "http://ai-sast"
  DATAJOB_WEBHOOK_URL: "https://discord.com/api/webhooks/1329072846584152136/jeAtA2by8dvd0exqSfX-rtBRdGO6Y-K1K-tx0y4PP16zFYbCP7Uj7Hc61fpXwfEzA15L"
  AWS_API_UPLOAD_S3_BUCKET: "cdefense-api-swagger"
  AWS_API_UPLOAD_S3_REGION: "us-west-2"