apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <CLUSTER-NAME>
  region: <REGION>

vpc:
  cidr: <CIDR>

managedNodeGroups:
  - name: cdefense
    labels: { label: cdefense }
    volumeEncrypted: true
    disableIMDSv1: true
    instanceType: "t3.xlarge"
    desiredCapacity: 1
    privateNetworking: true
    minSize: 1
    maxSize: 4
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/<CLUSTER-NAME>: "owned"
  - name: external
    labels: { label: external }
    volumeEncrypted: true
    disableIMDSv1: true
    instanceType: "t3.medium"
    desiredCapacity: 1
    privateNetworking: true
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/<CLUSTER-NAME>: "owned"
  - name: jobs
    labels: { label: job }
    spot: true
    volumeEncrypted: true
    disableIMDSv1: true
    instanceTypes: ["t3.xlarge"]
    desiredCapacity: 1
    privateNetworking: true
    minSize: 1
    maxSize: 4
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/<CLUSTER-NAME>: "owned"
