---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: {{ .Values.keycloak.service.type }}
  selector:
    app: keycloak
  ports:
    {{ .Values.keycloak.service.ports | toYaml | nindent 2 }}
