apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <CLUSTER-NAME>
  region: <REGION>

vpc:
  cidr: <CIDR>

managedNodeGroups:
  - name: cdefense
    # labels: { label: cdefense }
    volumeEncrypted: true
    instanceType: "t3.xlarge"
    desiredCapacity: 1
    privateNetworking: true
    minSize: 1
    maxSize: 4
  - name: jobs
    labels: { label: job }
    spot: true
    volumeEncrypted: true
    instanceTypes: ["t3.xlarge"]
    desiredCapacity: 1
    privateNetworking: true
    minSize: 1
    maxSize: 4
