{{ if .Values.uptime.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: uptime
  labels:
    app: uptime
spec:
  ports:
  - name: uptime
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: uptime
  type: NodePort
{{ end }}